name: 'Thank You Action'
description: 'Display "Thank You" to new Pull Request'
author: 'Nisarg Vadgama'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API Token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
